df<- read_csv("Data Set- Inc5000 Company List_2014.csv")
install.packages("tidyverse")
library(tidyverse)
str(df)
dim(df)
colSums(is.na(df))
drops <- c('_input')
drops
df <- df[ ,!(names(df) %in% drops)]
View(df)
df <- na.omit(df)
dim(df)
df <-df %>% distinct(id, .keep_all = TRUE)
dim(df)
df$growth <- round(df$growth ,digit=2)
head(df)
library(ggplot2)
ggplot(df, aes(x=revenue, y=growth)) + geom_boxplot(outlier.colour = "blue", outlier.shape = 1)+ scale_x_continuous(labels = scales::comma)+coord_cartesian(ylim = c(0, 1000))
Q1 <- quantile(df$growth, .25)
Q3 <- quantile(df$growth, .75)
IQR <- IQR(df$growth)
no_outliers <- subset(df, df$growth> (Q1 - 1.5*IQR) & df$growth< (Q3 + 1.5*IQR))
summary(no_outliers)
dim(no_outliers)
Q1 <- quantile(no_outliers$revenue, .25)
Q3 <- quantile(no_outliers$revenue, .75)
IQR <- IQR(no_outliers$revenue)
no_outliers <- subset(no_outliers, no_outliers$revenue> (Q1 - 1.5*IQR) & no_outliers$revenue< (Q3 + 1.5*IQR))
dim(no_outliers)
Q1 <- quantile(no_outliers$workers, .25)
Q3 <- quantile(no_outliers$workers, .75)
IQR <- IQR(no_outliers$workers)
ggplot(no_outliers, aes(x=rank, y=workers)) + geom_point()+ scale_y_continuous(labels=scales::comma)+coord_cartesian(ylim = c(0, 1000))
no_outliers <- subset(no_outliers, no_outliers$workers> (Q1 - 1.5*IQR) & no_outliers$workers< (Q3 + 1.5*IQR))
dim(no_outliers)
ggplot(no_outliers, aes(x=rank, y=workers)) + geom_point()+scale_colour_brewer(palette="Spectral")+ scale_y_continuous(labels=scales::comma)+coord_cartesian(ylim = c(0, 300))
ggplot(no_outliers, aes(x=yrs_on_list)) + geom_bar(color="green")+coord_cartesian(ylim = c(0, 1500), xlim=c(0,15))
write.csv(no_outliers, "clean_df.csv")
cor(no_outliers$growth,no_outliers$revenue)
order(no_outliers2$growth)
